-- =============================================================================
-- Global exercise library seed (org_id = null, is_custom = false)
--
-- Idempotent: re-running skips exercises whose name already exists in the
-- global library. Applied automatically by `supabase db reset`.
-- =============================================================================

insert into public.exercises (name, category, muscle_groups, equipment, description, instructions)
values

-- ---------------------------------------------------------------------------
-- STRENGTH
-- ---------------------------------------------------------------------------
('Back Squat', 'strength', '{quads,glutes,hamstrings,core}', '{barbell}',
 'Foundational bilateral lower-body strength lift.',
 'Bar on upper traps, feet shoulder-width. Brace, sit hips back and down to at least parallel, drive up through the mid-foot keeping chest tall.'),
('Front Squat', 'strength', '{quads,glutes,core}', '{barbell}',
 'Quad-dominant squat that demands an upright torso and strong trunk.',
 'Bar racked on front delts with high elbows. Squat between the hips keeping the torso vertical, then drive up.'),
('Goblet Squat', 'strength', '{quads,glutes,core}', '{dumbbell,kettlebell}',
 'Beginner-friendly squat pattern that reinforces depth and posture.',
 'Hold a dumbbell or kettlebell at the chest. Sit down between the knees, elbows inside knees at the bottom, stand tall.'),
('Trap Bar Deadlift', 'strength', '{quads,glutes,hamstrings,back}', '{trap_bar}',
 'Shoulder-friendly hinge/squat hybrid; a staple max-strength lift for throwers.',
 'Stand centered in the bar, grip handles, flat back. Push the floor away and stand tall, then lower under control.'),
('Conventional Deadlift', 'strength', '{hamstrings,glutes,back,core}', '{barbell}',
 'Posterior-chain dominant pull from the floor.',
 'Bar over mid-foot, hinge to grip just outside knees. Brace, pull slack out of the bar, and drive hips forward to lockout.'),
('Romanian Deadlift', 'strength', '{hamstrings,glutes,back}', '{barbell}',
 'Hip hinge emphasizing eccentric hamstring loading.',
 'Start standing, soft knees. Push hips back sliding the bar down the thighs until hamstrings are loaded, then drive hips through.'),
('Dumbbell RDL', 'strength', '{hamstrings,glutes}', '{dumbbell}',
 'Dumbbell variation of the Romanian deadlift.',
 'Hold dumbbells in front of the thighs. Hinge at the hips with a neutral spine, feel the hamstring stretch, return to standing.'),
('Single-Leg RDL', 'strength', '{hamstrings,glutes,core}', '{dumbbell,kettlebell}',
 'Unilateral hinge building hip stability needed for the stride and landing leg.',
 'Balance on one leg, hinge forward while the free leg extends behind. Keep hips square, return to standing.'),
('Rear-Foot Elevated Split Squat', 'strength', '{quads,glutes}', '{dumbbell}',
 'Unilateral leg strength builder (Bulgarian split squat).',
 'Rear foot on a bench, front foot out in front. Lower the back knee toward the floor, drive up through the front heel.'),
('Walking Lunge', 'strength', '{quads,glutes,hamstrings}', '{dumbbell,bodyweight}',
 'Dynamic unilateral strength and stability.',
 'Step forward into a lunge, back knee just off the ground, drive through the front leg into the next step.'),
('Lateral Lunge', 'strength', '{quads,glutes}', '{dumbbell,bodyweight}',
 'Frontal-plane strength and adductor mobility.',
 'Step wide to the side, sit back into the working hip with the other leg straight. Push back to start.'),
('Step-Up', 'strength', '{quads,glutes}', '{dumbbell,plyo_box}',
 'Unilateral strength with minimal spinal loading.',
 'Place one foot on a box, drive through that heel to stand on top, control the descent.'),
('Hip Thrust', 'strength', '{glutes,hamstrings}', '{barbell}',
 'Direct glute strength for hip extension power.',
 'Upper back on a bench, bar over hips. Drive hips up to full extension squeezing glutes, lower under control.'),
('Glute Bridge', 'strength', '{glutes,hamstrings,core}', '{bodyweight}',
 'Bodyweight hip extension; great activation or regression.',
 'Lie on back, knees bent. Drive through heels to lift hips, squeeze glutes at the top, lower slowly.'),
('Nordic Hamstring Curl', 'strength', '{hamstrings}', '{bodyweight}',
 'Eccentric hamstring exercise shown to reduce hamstring strain risk.',
 'Kneel with ankles anchored. Lower the torso forward as slowly as possible, catch with hands, push back up.'),
('Bench Press', 'strength', '{chest,shoulders,arms}', '{barbell}',
 'Horizontal pressing strength.',
 'Shoulder blades pinned back, feet planted. Lower the bar to the lower chest, press back up. Use moderate volume for pitchers.'),
('Dumbbell Bench Press', 'strength', '{chest,shoulders,arms}', '{dumbbell}',
 'Pressing variation allowing natural shoulder path.',
 'Press dumbbells from chest to lockout, allowing slight rotation of the hands. Control the lowering phase.'),
('Landmine Press', 'strength', '{shoulders,chest,core}', '{landmine}',
 'Shoulder-friendly angled press, popular with overhead athletes.',
 'Hold the bar end at the shoulder in a half-kneeling or split stance. Press up and out, letting the shoulder blade move freely.'),
('Push-Up', 'strength', '{chest,shoulders,arms,core}', '{bodyweight}',
 'Closed-chain press that allows free scapular movement.',
 'Hands under shoulders, body in a straight line. Lower chest to the floor, push away fully at the top.'),
('Pull-Up', 'strength', '{back,arms}', '{pull_up_bar}',
 'Vertical pulling strength.',
 'Hang with arms straight. Pull the chest toward the bar driving elbows down, lower to a full hang.'),
('Chin-Up', 'strength', '{back,arms}', '{pull_up_bar}',
 'Supinated-grip vertical pull with more biceps involvement.',
 'Palms facing you, shoulder-width grip. Pull chin over the bar, lower to full extension.'),
('Inverted Row', 'strength', '{back,arms,core}', '{barbell,bodyweight}',
 'Bodyweight horizontal pull.',
 'Hang under a racked bar with a straight body. Pull chest to the bar squeezing shoulder blades, lower slowly.'),
('Single-Arm Dumbbell Row', 'strength', '{back,arms}', '{dumbbell}',
 'Unilateral horizontal pull for upper-back strength.',
 'One hand and knee on a bench, flat back. Row the dumbbell toward the hip, pause, lower to a full stretch.'),
('Chest-Supported Row', 'strength', '{back,shoulders}', '{dumbbell}',
 'Horizontal row without lower-back fatigue.',
 'Lie prone on an incline bench. Row dumbbells up, squeezing shoulder blades together, lower under control.'),
('Seated Cable Row', 'strength', '{back,arms}', '{cable}',
 'Horizontal pull with constant tension.',
 'Sit tall, pull the handle to the stomach driving elbows back, let the shoulder blades protract on the return.'),
('Lat Pulldown', 'strength', '{back,arms}', '{cable,machine}',
 'Vertical pull for lat strength.',
 'Grip slightly wider than shoulders, pull the bar to the upper chest with elbows driving down, return slowly.'),
('Farmer Carry', 'strength', '{full_body,core,arms}', '{dumbbell,kettlebell}',
 'Loaded carry building grip, trunk stability, and work capacity.',
 'Hold heavy weights at the sides, stand tall, and walk with short controlled steps for distance or time.'),
('Suitcase Carry', 'strength', '{core,arms}', '{dumbbell,kettlebell}',
 'Single-side carry that challenges anti-lateral-flexion.',
 'Hold one weight at your side, stay perfectly upright, walk the prescribed distance, switch hands.'),
('Copenhagen Plank', 'strength', '{core}', '{bodyweight}',
 'Adductor strength exercise; protects the groin during rotation.',
 'Side plank with the top leg on a bench and bottom leg free. Hold with hips high for time.'),

-- ---------------------------------------------------------------------------
-- POWER
-- ---------------------------------------------------------------------------
('Hang Clean', 'power', '{full_body}', '{barbell}',
 'Olympic lift derivative for triple extension power.',
 'From mid-thigh, explosively extend hips, knees, and ankles, shrug and pull under to catch in a front rack.'),
('Hang High Pull', 'power', '{full_body,back,shoulders}', '{barbell}',
 'Triple extension power without the catch.',
 'From the hang, explode up and pull the bar to chest height with elbows high.'),
('Trap Bar Jump', 'power', '{quads,glutes,hamstrings}', '{trap_bar}',
 'Loaded jump for lower-body power.',
 'Light trap bar load. Dip and jump explosively, land softly and reset each rep.'),
('Kettlebell Swing', 'power', '{glutes,hamstrings,core}', '{kettlebell}',
 'Ballistic hip hinge for posterior-chain power.',
 'Hike the bell back between the legs, snap hips forward to float it to chest height. Let it fall and repeat.'),
('Med Ball Rotational Scoop Toss', 'power', '{core,full_body}', '{med_ball}',
 'Rotational power that mirrors hitting and throwing hip-to-shoulder sequencing.',
 'Stand sideways to a wall, load the back hip, then rotate explosively and release the ball into the wall.'),
('Med Ball Shotput Throw', 'power', '{core,shoulders,full_body}', '{med_ball}',
 'Rotational upper-body power from a throwing posture.',
 'Ball at the back shoulder, load the back hip, rotate and push the ball into the wall like a shotput.'),
('Med Ball Overhead Slam', 'power', '{core,full_body}', '{med_ball}',
 'Total-body power and trunk flexion.',
 'Reach the ball overhead onto toes, then slam it to the ground as hard as possible. Catch and repeat.'),
('Med Ball Chest Pass', 'power', '{chest,arms}', '{med_ball}',
 'Horizontal upper-body power.',
 'Athletic stance, ball at chest. Explosively push the ball into the wall and catch the rebound.'),
('Med Ball Step-Behind Rotational Throw', 'power', '{core,full_body}', '{med_ball}',
 'Rotational throw with a crossover step to add momentum, mimicking the pitching stride.',
 'Step the back foot behind the front, load the hip, then rotate and release into the wall.'),
('Med Ball Overhead Throw', 'power', '{core,shoulders,back}', '{med_ball}',
 'Soccer-style overhead throw for trunk and lat power.',
 'Facing the wall, take the ball overhead and step forward, throwing with the trunk and lats.'),
('Med Ball Backward Toss', 'power', '{glutes,hamstrings,back}', '{med_ball}',
 'Triple extension power for distance.',
 'Hold the ball between the legs, dip, then extend explosively and throw the ball backward overhead.'),
('Landmine Rotation', 'power', '{core,shoulders}', '{landmine}',
 'Anti-rotation to rotation strength through the trunk.',
 'Hold the bar end at arms length, rotate it from hip to hip pivoting the feet, controlling with the trunk.'),
('Cable Rotational Chop', 'power', '{core,shoulders}', '{cable}',
 'High-to-low rotational strength.',
 'Pull the cable diagonally across the body from high to low, rotating through the hips and trunk.'),

-- ---------------------------------------------------------------------------
-- PLYOMETRIC
-- ---------------------------------------------------------------------------
('Box Jump', 'plyometric', '{quads,glutes,hamstrings}', '{plyo_box}',
 'Concentric-focused jump with a low landing impact.',
 'Swing arms and jump onto the box, landing softly in a quarter squat. Step down each rep.'),
('Broad Jump', 'plyometric', '{quads,glutes,hamstrings}', '{bodyweight}',
 'Horizontal power and a common testing metric.',
 'Swing arms and jump forward as far as possible, stick the landing.'),
('Lateral Bound', 'plyometric', '{glutes,quads}', '{bodyweight}',
 'Frontal-plane power that mirrors the drive off the rubber.',
 'Push off one leg sideways, land on the opposite leg and stick it for a beat before bounding back.'),
('Heiden Skater Hop', 'plyometric', '{glutes,quads}', '{bodyweight}',
 'Continuous lateral bounding for elastic power.',
 'Bound side to side like a speed skater, landing softly and immediately rebounding.'),
('Depth Jump', 'plyometric', '{quads,glutes,hamstrings}', '{plyo_box}',
 'Advanced reactive jump training the stretch-shortening cycle.',
 'Step off a low box, land, and immediately jump as high as possible with minimal ground contact.'),
('Pogo Hops', 'plyometric', '{quads}', '{bodyweight}',
 'Ankle stiffness and elasticity drill.',
 'Small rapid hops on the balls of the feet with stiff ankles and minimal knee bend.'),
('Single-Leg Box Jump', 'plyometric', '{quads,glutes}', '{plyo_box}',
 'Unilateral jumping power.',
 'Jump from one leg onto a low box, land on both feet softly. Step down.'),
('Split Squat Jump', 'plyometric', '{quads,glutes}', '{bodyweight}',
 'Explosive unilateral jump switching legs midair.',
 'From a lunge, jump up and switch legs in the air, landing softly in the opposite lunge.'),
('Plyo Push-Up', 'plyometric', '{chest,shoulders,arms}', '{bodyweight}',
 'Upper-body reactive power.',
 'Lower into a push-up and explode so the hands leave the ground, land softly and repeat.'),
('Rotational Hop', 'plyometric', '{core,quads,glutes}', '{bodyweight}',
 'Jump with a 90-degree turn to build rotational landing control.',
 'Jump and rotate 90 degrees in the air, land softly in an athletic stance. Alternate directions.'),

-- ---------------------------------------------------------------------------
-- MOBILITY
-- ---------------------------------------------------------------------------
('Worlds Greatest Stretch', 'mobility', '{full_body}', '{bodyweight}',
 'Total-body dynamic warm-up flow hitting hips, T-spine, and hamstrings.',
 'Lunge forward, place the same-side elbow to the instep, rotate and reach to the sky, then straighten the front leg.'),
('90/90 Hip Switch', 'mobility', '{glutes}', '{bodyweight}',
 'Hip internal and external rotation mobility.',
 'Sit with both knees bent at 90 degrees to one side. Rotate the knees to the other side keeping the chest tall.'),
('Open Book T-Spine Rotation', 'mobility', '{back,shoulders}', '{bodyweight}',
 'Thoracic rotation mobility for throwing and hitting.',
 'Lie on your side, knees bent. Open the top arm across the body, following with the eyes, and rotate the upper back.'),
('Quadruped T-Spine Rotation', 'mobility', '{back}', '{bodyweight}',
 'Thoracic rotation with the lumbar spine locked.',
 'On hands and knees, hand behind head, rotate the elbow down to the opposite wrist then up to the ceiling.'),
('Cat-Cow', 'mobility', '{back,core}', '{bodyweight}',
 'Spinal flexion and extension control.',
 'On hands and knees, alternate rounding the spine up and arching it down, moving segment by segment.'),
('Hip Flexor Stretch', 'mobility', '{quads,glutes}', '{bodyweight}',
 'Half-kneeling hip flexor lengthening.',
 'Half-kneeling, tuck the pelvis and squeeze the back glute, shifting forward until the front of the hip stretches.'),
('Couch Stretch', 'mobility', '{quads}', '{bodyweight}',
 'Deep quad and hip flexor stretch.',
 'Back knee against a wall with the shin up the wall, front foot planted. Stay tall and squeeze the glute.'),
('Adductor Rock Back', 'mobility', '{glutes}', '{bodyweight}',
 'Groin mobility for lateral movement and stride length.',
 'On hands and knees with one leg out to the side, rock the hips back toward the heel keeping the back flat.'),
('Deep Squat Hold', 'mobility', '{quads,glutes}', '{bodyweight}',
 'Ankle, hip, and T-spine mobility in a deep squat.',
 'Sit into the bottom of a squat, elbows pushing knees out, chest tall. Breathe and hold.'),
('Sleeper Stretch', 'mobility', '{shoulders}', '{bodyweight}',
 'Posterior shoulder capsule internal rotation stretch. Use gently.',
 'Lie on the throwing side, arm at 90 degrees. Gently press the forearm toward the floor until a mild stretch is felt.'),
('Cross-Body Stretch', 'mobility', '{shoulders}', '{bodyweight}',
 'Posterior shoulder stretch.',
 'Pull the arm across the chest with the opposite hand, keeping the shoulder blade pinned down.'),
('Wall Slide', 'mobility', '{shoulders,back}', '{bodyweight}',
 'Overhead mobility with scapular upward rotation.',
 'Back and forearms against a wall, slide the arms overhead keeping contact, then return.'),
('Thread the Needle', 'mobility', '{back,shoulders}', '{bodyweight}',
 'T-spine rotation and posterior shoulder opener.',
 'On hands and knees, reach one arm under the body as far as possible, then rotate it up to the ceiling.'),
('Foam Roll Thoracic Extension', 'mobility', '{back}', '{foam_roller}',
 'Soft tissue and extension mobility for the upper back.',
 'Roller under the upper back, hands behind head. Extend over the roller segment by segment.'),
('Foam Roll Lats', 'mobility', '{back}', '{foam_roller}',
 'Soft tissue work for the lats, which often restrict overhead motion.',
 'Lie on your side with the roller under the armpit, arm overhead. Roll slowly from the armpit to mid-ribs.'),
('Hamstring Floss', 'mobility', '{hamstrings}', '{band,bodyweight}',
 'Dynamic hamstring mobility.',
 'Lie on back with a band around one foot. Alternate straightening and bending the knee with the leg raised.'),
('Ankle Rocker', 'mobility', '{quads}', '{bodyweight}',
 'Ankle dorsiflexion mobility.',
 'Half-kneeling facing a wall, drive the front knee forward over the toes without lifting the heel.'),

-- ---------------------------------------------------------------------------
-- ARM CARE
-- ---------------------------------------------------------------------------
('Band Pull-Apart', 'arm_care', '{shoulders,back}', '{band}',
 'Scapular retraction and rear-delt endurance.',
 'Hold a band at shoulder height, arms straight. Pull it apart until it touches the chest, return slowly.'),
('Band External Rotation', 'arm_care', '{shoulders}', '{band}',
 'Rotator cuff strength at the side.',
 'Elbow pinned to the side at 90 degrees, rotate the forearm outward against the band, return slowly.'),
('Band Internal Rotation', 'arm_care', '{shoulders}', '{band}',
 'Internal rotator strength at the side.',
 'Elbow at the side at 90 degrees, rotate the forearm inward across the body against the band.'),
('90/90 Band External Rotation', 'arm_care', '{shoulders}', '{band}',
 'External rotation in the throwing position.',
 'Arm abducted to 90 degrees with elbow bent 90. Rotate the forearm up and back against the band, control the return.'),
('Jaeger Band Forward Fly', 'arm_care', '{shoulders,chest}', '{band}',
 'Part of the J-Band routine; warms up the front of the shoulder.',
 'Facing away from the anchor, arms out wide, bring the arms together in front with straight elbows.'),
('Jaeger Band Reverse Fly', 'arm_care', '{shoulders,back}', '{band}',
 'Part of the J-Band routine; posterior shoulder activation.',
 'Facing the anchor, arms in front, pull the arms out wide with straight elbows squeezing shoulder blades.'),
('Jaeger Band Throwing Deceleration', 'arm_care', '{shoulders}', '{band}',
 'Mimics the arm path of the follow-through to train deceleration.',
 'Facing the anchor, start at release point and slowly let the band pull the arm back to the cocked position.'),
('Jaeger Band Throwing Acceleration', 'arm_care', '{shoulders,arms}', '{band}',
 'Mimics the arm path of the throw against light resistance.',
 'Facing away from the anchor, take the arm from the cocked position through the throwing motion to release.'),
('Prone Y Raise', 'arm_care', '{shoulders,back}', '{dumbbell,bodyweight}',
 'Lower trap and scapular upward rotation strength.',
 'Lie prone on an incline bench, thumbs up. Raise arms overhead into a Y, hold briefly, lower.'),
('Prone T Raise', 'arm_care', '{shoulders,back}', '{dumbbell,bodyweight}',
 'Middle trap and rear delt strength.',
 'Lie prone, arms out to the sides with thumbs up. Squeeze shoulder blades and raise arms into a T.'),
('Prone W Raise', 'arm_care', '{shoulders,back}', '{bodyweight}',
 'Scapular retraction with external rotation.',
 'Lie prone, elbows bent at 90 degrees. Squeeze shoulder blades and lift elbows and hands into a W.'),
('Side-Lying External Rotation', 'arm_care', '{shoulders}', '{dumbbell}',
 'Classic rotator cuff strengthener.',
 'Lie on the non-working side, towel under the elbow. Rotate a light dumbbell up keeping the elbow at the side.'),
('Prone 90/90 External Rotation', 'arm_care', '{shoulders}', '{dumbbell}',
 'Rotator cuff strength in an abducted position.',
 'Lie prone with the arm off the bench at 90/90. Rotate the forearm up until parallel with the floor, lower slowly.'),
('Scap Push-Up', 'arm_care', '{shoulders,back}', '{bodyweight}',
 'Serratus anterior activation for scapular control.',
 'In a push-up position with locked elbows, let the shoulder blades pinch together, then push them apart.'),
('Serratus Wall Slide', 'arm_care', '{shoulders}', '{band,bodyweight}',
 'Upward rotation and serratus activation.',
 'Forearms on the wall with a band around the wrists, slide up the wall while pushing slightly into it.'),
('Face Pull', 'arm_care', '{shoulders,back}', '{cable,band}',
 'Rear delt and external rotation strength.',
 'Pull the rope toward the face with elbows high, finishing with hands beside the ears.'),
('Wrist Flexion and Extension', 'arm_care', '{arms}', '{dumbbell}',
 'Forearm strength to support the elbow.',
 'Forearm on a bench, curl the wrist up and lower it with a light dumbbell. Repeat palm down.'),
('Pronation and Supination', 'arm_care', '{arms}', '{dumbbell}',
 'Forearm rotation strength that protects the UCL.',
 'Hold one end of a dumbbell or hammer, rotate the forearm slowly palm up to palm down.'),
('Rice Bucket', 'arm_care', '{arms}', '{bodyweight}',
 'Forearm and grip endurance circuit.',
 'Bury hands in a bucket of rice and perform grips, wrist circles, and rotations for time.'),
('Plate Pinch Hold', 'arm_care', '{arms}', '{bodyweight}',
 'Finger and grip strength.',
 'Pinch two smooth-sided plates together with the fingertips and hold for time.'),
('Rhythmic Stabilization', 'arm_care', '{shoulders}', '{bodyweight}',
 'Partner perturbations for dynamic shoulder stability.',
 'Hold the arm in the throwing position while a partner applies quick light pushes in random directions.'),
('Weighted Ball Wall Dribble', 'arm_care', '{shoulders}', '{weighted_ball}',
 'Rotator cuff endurance with a small plyo ball.',
 'Hold a plyo ball against a wall at 90/90 and dribble it in small rapid circles.'),

-- ---------------------------------------------------------------------------
-- CONDITIONING
-- ---------------------------------------------------------------------------
('Tempo Runs', 'conditioning', '{full_body}', '{bodyweight}',
 'Aerobic conditioning at moderate effort.',
 'Run 100 yards at about 65-75 percent, walk back, and repeat for the prescribed reps.'),
('Assault Bike Intervals', 'conditioning', '{full_body}', '{machine}',
 'Low-impact high-intensity intervals.',
 'Sprint for the work interval, then pedal easily for recovery. Repeat for the prescribed rounds.'),
('Sled Push', 'conditioning', '{quads,glutes,full_body}', '{sled}',
 'Concentric-only work capacity and acceleration strength.',
 'Lean into the sled with straight arms and drive with short powerful steps for the distance.'),
('Sled Drag', 'conditioning', '{hamstrings,glutes}', '{sled}',
 'Low-stress posterior-chain conditioning.',
 'Attach a strap and walk backward or forward dragging the sled for distance.'),
('Shuttle Run', 'conditioning', '{full_body}', '{bodyweight}',
 'Change-of-direction conditioning.',
 'Run back and forth between cones touching each line for the prescribed distance or time.'),
('Rowing Machine Intervals', 'conditioning', '{full_body,back}', '{machine}',
 'Total-body conditioning.',
 'Row hard for the work interval, recover easy, repeat. Drive with legs, then hips, then arms.'),
('Jump Rope', 'conditioning', '{full_body}', '{bodyweight}',
 'Footwork, rhythm, and conditioning.',
 'Skip rope on the balls of the feet with minimal knee bend for the prescribed time.'),
('Bear Crawl', 'conditioning', '{full_body,core,shoulders}', '{bodyweight}',
 'Crawling pattern for shoulder stability and conditioning.',
 'On hands and feet with knees just off the ground, crawl forward with opposite hand and foot.'),

-- ---------------------------------------------------------------------------
-- SPEED / AGILITY
-- ---------------------------------------------------------------------------
('10-Yard Sprint', 'speed', '{full_body}', '{bodyweight}',
 'Acceleration training for the first steps out of the box or on a steal.',
 'From a staggered or athletic stance, sprint 10 yards at max effort. Full rest between reps.'),
('60-Yard Sprint', 'speed', '{full_body}', '{bodyweight}',
 'The standard baseball speed test distance.',
 'From a standing start, sprint 60 yards at max effort. Take full recovery between reps.'),
('Flying 10s', 'speed', '{full_body}', '{bodyweight}',
 'Max velocity sprint training.',
 'Build up over 20 yards, then sprint at max speed through a 10-yard zone.'),
('Base Stealing Starts', 'speed', '{full_body}', '{bodyweight}',
 'Crossover start and acceleration from a lead.',
 'From a lead stance, pivot and crossover step, then sprint 15-20 yards.'),
('Home to First Sprint', 'speed', '{full_body}', '{bat}',
 'Swing-and-run acceleration out of the box.',
 'Take a dry swing and sprint through first base, running through the bag.'),
('Pro Agility (5-10-5)', 'speed', '{full_body}', '{bodyweight}',
 'Lateral change-of-direction test and drill.',
 'Straddle the line, sprint 5 yards right, 10 yards left, 5 yards back through the start.'),
('Lateral Shuffle', 'speed', '{quads,glutes}', '{bodyweight}',
 'Lateral movement for infield range.',
 'Stay low in an athletic stance and shuffle laterally without crossing the feet.'),
('A-Skip', 'speed', '{full_body}', '{bodyweight}',
 'Sprint mechanics drill for posture and front-side mechanics.',
 'Skip forward driving the knee up and the foot down under the hip, with opposite arm action.'),

-- ---------------------------------------------------------------------------
-- THROWING
-- ---------------------------------------------------------------------------
('Long Toss', 'throwing', '{shoulders,full_body}', '{baseball}',
 'Progressive distance throwing to build arm strength and endurance.',
 'Gradually extend distance with arcing throws, then pull down throwing on a line back toward your partner.'),
('Flat Ground Throwing', 'throwing', '{shoulders,full_body}', '{baseball}',
 'Pitching from flat ground at a prescribed intensity.',
 'From 60 feet, work through the pitch mix from the stretch and windup at the prescribed effort.'),
('Bullpen Session', 'throwing', '{shoulders,full_body}', '{baseball}',
 'Mound throwing at a prescribed pitch count and intensity.',
 'Throw the prescribed pitch count and mix off the mound, tracking pitches and intent.'),
('Catch Play Progression', 'throwing', '{shoulders}', '{baseball}',
 'Structured warm-up catch.',
 'Start close with wrist flips, progress through knee throws and standing throws as distance increases.'),
('Pivot Pickoff Drill', 'throwing', '{shoulders,core}', '{weighted_ball}',
 'Plyo ball drill reinforcing hip-to-shoulder separation.',
 'Start sideways, rotate toward the back hip, then pivot and throw the plyo ball into a wall.'),
('Reverse Throw', 'throwing', '{shoulders,back}', '{weighted_ball}',
 'Plyo ball drill training deceleration of the arm.',
 'Facing away from the wall, rotate and throw the plyo ball backward into the wall with the throwing arm.'),
('Rocker Throw', 'throwing', '{shoulders,full_body}', '{weighted_ball}',
 'Plyo ball drill to sync lower and upper body timing.',
 'In a wide stance facing the wall, rock back and forth to build rhythm then throw into the wall.'),
('Walking Windup', 'throwing', '{full_body}', '{weighted_ball,baseball}',
 'Momentum-building throw for intent and sequencing.',
 'Walk into a throw, crossing over then striding to the target and throwing with intent.'),
('Wrist Flicks', 'throwing', '{arms}', '{baseball}',
 'Short-range throws focusing on wrist action and spin.',
 'From 10-15 feet with the elbow supported, flick the ball to a partner focusing on clean backspin.'),
('Infield Throws Across the Diamond', 'throwing', '{shoulders,full_body}', '{baseball}',
 'Position-specific throwing accuracy and arm strength.',
 'Field a roll or fungo, set the feet, and throw to first base on a line.'),
('Outfield Crow Hop Throws', 'throwing', '{shoulders,full_body}', '{baseball}',
 'Crow hop footwork for strong outfield throws.',
 'Field the ball moving forward, crow hop to gain momentum, and throw on a line to the cutoff.'),

-- ---------------------------------------------------------------------------
-- HITTING
-- ---------------------------------------------------------------------------
('Tee Work', 'hitting', '{full_body,core}', '{bat,tee,baseball}',
 'Foundational swing reps from a stationary ball.',
 'Set the tee at the prescribed location, take focused swings driving the ball on a line.'),
('Front Toss', 'hitting', '{full_body,core}', '{bat,baseball}',
 'Short-distance soft toss working timing and barrel accuracy.',
 'A partner tosses underhand from behind an L-screen. Drive the ball to all fields.'),
('Side Toss', 'hitting', '{full_body,core}', '{bat,baseball}',
 'Toss from the side to work on staying through the ball.',
 'Partner kneels to the side and tosses into the hitting zone. Drive the ball into the net.'),
('Batting Practice', 'hitting', '{full_body,core}', '{bat,baseball}',
 'Live BP rounds from a pitcher or coach.',
 'Hit the prescribed rounds with a focus each round (e.g. opposite field, line drives, situational).'),
('Machine Velocity Training', 'hitting', '{full_body,core}', '{bat,baseball,machine}',
 'High-velocity or breaking ball machine reps.',
 'Set the machine to game speed or the prescribed pitch type and take focused rounds.'),
('One-Hand Drill (Top Hand)', 'hitting', '{arms,core}', '{bat,tee,baseball}',
 'Isolates the top hand to improve barrel control.',
 'Choke up and swing with only the top hand off a tee, focusing on a short path through the ball.'),
('One-Hand Drill (Bottom Hand)', 'hitting', '{arms,core}', '{bat,tee,baseball}',
 'Isolates the lead arm to train a direct path to the ball.',
 'Swing with only the bottom hand off a tee, keeping the barrel above the hands.'),
('High Tee', 'hitting', '{full_body,core}', '{bat,tee,baseball}',
 'Trains a level-to-slightly-up barrel path on the top of the zone.',
 'Set the tee at the top of the zone and drive line drives without chopping down.'),
('Overload/Underload Bat Swings', 'hitting', '{full_body,core}', '{bat}',
 'Bat speed training with heavier and lighter bats.',
 'Alternate sets of max-intent swings with a heavy bat, a light bat, and your game bat.'),
('Dry Swings', 'hitting', '{full_body,core}', '{bat}',
 'Swing reps without a ball for movement pattern work.',
 'Take full-effort swings focusing on a single movement cue each set.'),
('Pitch Recognition Drill', 'hitting', '{full_body}', '{bat,baseball}',
 'Trains recognizing spin and location early.',
 'Track live or machine pitches calling out pitch type and location before deciding to swing.'),
('Bunting Practice', 'hitting', '{arms}', '{bat,baseball}',
 'Sacrifice and drag bunt technique.',
 'Square or pivot early, bat at the top of the zone, and deaden the ball down each baseline.')

on conflict (lower(name)) where org_id is null do nothing;
